### ISSUE TITLE
BUG | TypeError: Cannot read property 'Reader' of undefined

### ISSUE THREAD

**Issue by louisgv** [googleapis/nodejs-secret-manager#169]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: Windows 10
  - Node.js version: 12.18.4
  - npm version: 6.14.6
  - `@google-cloud/secret-manager` version: ^3.2.0

#### Steps to reproduce

  1. Setup a secret in Secret Manager, and added google credentials with the `Secret Manager Secret Accessor (1)`
  2. Test with the code below:

```
import { SecretManagerServiceClient } from "@google-cloud/secret-manager"

async function main() {
  const secretName = "projects/123456789/secrets/Test/versions/1"

  const secretClient = new SecretManagerServiceClient()

  const data = await secretClient.accessSecretVersion({
    name: secretName
  })

  const [secrets] = await secretClient.listSecrets({
    parent: "projects/123456789"
  })

  secrets.forEach((secret) => {
    const policy = secret.replication
    console.log(`${secret.name} (${policy})`)
  })

  console.log(data)

  const [accessResponse] = data

  // Extract the payload as a string.
  const responsePayload = accessResponse.payload.data.toString()
  // WARNING: Do not print the secret in a production environment - this
  // snippet is showing how to access the secret material.
  console.info(`Payload: ${responsePayload}`)
}

main()
```

 3. Received the error below: 

```

P:\Projects\considr\inQ\server\node_modules\@google-cloud\secret-manager\build\protos\protos.js:24
})(this, function($protobuf) {
  ^
TypeError: Cannot read property 'Reader' of undefined
    at P:\Projects\considr\inQ\server\node_modules\@google-cloud\secret-manager\build\protos\protos.js:28:29
    at P:\Projects\considr\inQ\server\node_modules\@google-cloud\secret-manager\build\protos\protos.js:22:26
    at Object.<anonymous> (P:\Projects\considr\inQ\server\node_modules\@google-cloud\secret-manager\build\protos\protos.js:24:3)     
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (P:\Projects\considr\inQ\server\node_modules\@google-cloud\secret-manager\src\index.ts:26:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
[nodemon] app crashed - waiting for file changes before starting...
```

> NOTE: The service account is also being used for other APIs such as Storage and Speech, which all works.

**Comment by louisgv** [comment]
Related: https://github.com/googleapis/nodejs-pubsub/issues/1082

**Comment by louisgv** [comment]
Tested on nodejs 10.21.0 and it worked. Maybe an incompatibility issue with 12.18?

**Comment by dsstewa** [comment]
We are also experiencing the same issue with 3.2.0 after installing "@google-cloud/tasks": "^2.1.1" It appears this release is not does not like working with other google packages. We had to downgrade to 3.1.0 to resolve the issue. Def a breaking bug.

**Comment by JustinBeckwith** [comment]
Thank you @louisgv for the Pub/Sub clue! Locally, I can get this code to work just fine with Node.js 10, 12, and 14.   I think this maybe is the hint:
https://github.com/googleapis/nodejs-pubsub/pull/1085

Can I trouble y'all to do a few things?
1. Run `npm ls google-gax`, and report the version.  Verify the code doesn't work. 
2. Run `npm update`, and `npm ls google-gax` again
3. Try to run your code again

I suspect the problem here is that the range we ask for in `package.json` for `google-gax` is only `^2.1.0`, but `^2.7.0` and up may be required.  If we can verify that's the fix, this is an easy fix both for you and for us :)

**Comment by 1N50MN14** [comment]
@JustinBeckwith 

Experiencing the same issue over here, had to downgrade to `3.1.0`.

`google-gax` version is `2.6.3`. yarn/npm update doesn't resolve the issue.

**Comment by 1N50MN14** [comment]
Update: Upgrading node to LTS / `14.15.0` resolves the issue,. But then it breaks for `@google-cloud/monitoring`, downgrading that for now.

**Comment by JustinBeckwith** [comment]
@1N50MN14 ok yarn is an interesting clue :). Can you please share:
- the original version of nodejs you're running that doesn't work
- whatever errors you're getting from monitoring

**Comment by 1N50MN14** [comment]
@JustinBeckwith Oh in which case you may completely take npm out of the equation ;)

Logs:

1.  Node `14.15.0` causes monitoring to throw the following error:
```
[1604764941237] ERROR	 (28635 on dfv): Cannot read property 'Reader' of undefined
    TypeError: Cannot read property 'Reader' of undefined
        at /home/am/dev/dfv/platform/api/auth/node_modules/@google-cloud/monitoring/build/protos/protos.js:28:29
        at /home/am/dev/dfv/platform/api/auth/node_modules/@google-cloud/monitoring/build/protos/protos.js:22:26
        at Object.<anonymous> (/home/am/dev/dfv/platform/api/auth/node_modules/@google-cloud/monitoring/build/protos/protos.js:24:3)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (/home/am/dev/dfv/platform/api/auth/node_modules/@google-cloud/monitoring/build/src/index.js:44:16)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)

```
2. Rolling back to the preceding node LTS `12.18.3`... actually *also* throws the same error from `monitoring`.  It was `secret-manager` doing that (per my initial feedback) *prior* to upgrading monitoring to latest.

I may have to double check my other containers as I use multiple gcp packages there... after figuring out this one.

Many thanks for the quick feedback!

**Comment by JustinBeckwith** [comment]
Ok, so trying to take this one step at a time, and try to identify the origin issue.  I created a repo here with a minimal snippet of code:
https://github.com/JustinBeckwith/secret-manager-169

My system setup:
- Node: v12.18.4
- OSX latest
- npm: 6.14.6

After cloning the repo, I can run:
```
$ node secret.js <my-project> <my-key-name> <my-key-version>
```

And ... it works for me 😱   @louisgv can I trouble you to clone my repo, and try this out?  I want to know if this exact thing works on your machine, and we can go backwards from there.
