### ISSUE TITLE
Is this compatible with Node10 Cloud Functions?

### ISSUE THREAD

**Issue by ESBA-salman** [googleapis/nodejs-secret-manager#20]
I wrote a cloud function which works fine in node8. But switching to node10 gives me an error. The API is enabled and works fine with node8. Can you please take a look?

Thanks

PERMISSION_DENIED: Secret Manager API has not been used in project xxxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/secretmanager.googleapis.com/overview?project=316838101533 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
    at Object.callErrorFromStatus (/srv/functions/node_modules/@google-cloud/secret-manager/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/srv/functions/node_modules/@google-cloud/secret-manager/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:194:15)
    at Http2CallStream.EventEmitter.emit (domain.js:459:23)
    at process.nextTick (/srv/functions/node_modules/@google-cloud/secret-manager/node_modules/@grpc/grpc-js/build/src/call-stream.js:97:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by bcoe** [comment]
@ESBA-salman I'm using Secret Manager in my own Node 10 cloud functions:

https://github.com/googleapis/repo-automation-bots/blob/master/packages/publish/src/publish.ts#L136

Is there a chance perhaps you've setup an environment variable incorrectly (double check that `316838101533` is the appropriate project number for starers).

**Comment by ESBA-salman** [comment]
Thanks, looks like it has to do with using process.env.GCP_PROJECT. Which seems to not work in Node10

**Comment by bcoe** [comment]
@ESBA-salman :+1: I'll see about opening an internal issue, I'm glad you found the solution.
