### ISSUE TITLE
Unidentified Error Appears in Ubuntu Version 14

### ISSUE THREAD

**Issue by prakasa-tkpd** [googleapis/nodejs-secret-manager#209]
I got different result in ubuntu 18 and 14. Everything running well in version 18. But I got this error below when using same version in ubuntu 14, is it really related with OS version ?:

istributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Opts:
```sh
const options = {
  credentials: cred,
  fallback: true,
};
```

```sh
no such type: google.rpc.ErrorInfo
    at Root.lookupType (./example/node_modules/.pnpm/registry.npmjs.org/protobufjs/6.10.2/node_modules/protobufjs/src/namespace.js:382:15)
    at FallbackErrorDecoder.decodeProtobufAny (./example/node_modules/.pnpm/registry.npmjs.org/google-gax/2.10.2/node_modules/google-gax/build/src/fallbackError.js:35:32)
    at ./example/node_modules/.pnpm/registry.npmjs.org/google-gax/2.10.2/node_modules/google-gax/build/src/fallbackError.js:50:56
    at Array.map (<anonymous>)
    at FallbackErrorDecoder.decodeRpcStatus (./example/node_modules/.pnpm/registry.npmjs.org/google-gax/2.10.2/node_modules/google-gax/build/src/fallbackError.js:50:37)
    at FallbackErrorDecoder.decodeErrorFromBuffer (./example/node_modules/.pnpm/registry.npmjs.org/google-gax/2.10.2/node_modules/google-gax/build/src/fallbackError.js:63:46)
    at ./example/node_modules/.pnpm/registry.npmjs.org/google-gax/2.10.2/node_modules/google-gax/build/src/fallback.js:323:57
    at processTicksAndRejections (internal/process/task_queues.js:97:5) with message no such type: google.rpc.ErrorInfo
```

any clue about this ?

**Comment by bcoe** [comment]
@prakasa-tkpd are you using the `pnpm` command line to install the project?

Could I bother you to try with `npm`, as this error actually looks like it might be related to an installation error.

**Comment by bcoe** [comment]
@prakasa-tkpd closing this issue since I haven't heard back from you.

Were you able to get things working using `npm`?
