### ISSUE TITLE
accessSecretVersion() throws INVALID_ARGUMENT

### ISSUE THREAD

**Issue by raman-nbg** [googleapis/nodejs-secret-manager#74]
#### Environment details

  - OS: macos
  - Node.js version: 12.10.0
  - npm version: 6.10.3
  - `@google-cloud/secret-manager` version: 2.0.1

#### Steps to reproduce

I'm using `accessSecretVersion()` to get a secret. Everytime I run this code, I get the following error:

```json
"details":"Resource ID [projects/688327991979/secrets/foobar] is not in a valid format.",
"metadata":{
  "internalRepr":{},
  "options":{}
},
"note":"Exception occurred in retry method that was not classified as transient",
"level":"error",
"stack":"Error: 3 INVALID_ARGUMENT: Resource ID [projects/688327991979/secrets/foobar] is not in a valid format.
    at Object.callErrorFromStatus (/Users/raman/dev/gitlab/gymtition/notification-service/node_modules/@google-cloud/secret-manager/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.<anonymous> (/Users/raman/dev/gitlab/gymtition/notification-service/node_modules/@google-cloud/secret-manager/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:214:15)
    at /Users/raman/dev/gitlab/gymtition/notification-service/node_modules/@google-cloud/secret-manager/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11)",
"message":"3 INVALID_ARGUMENT: Resource ID [projects/688327991979/secrets/foobar] is not in a valid format."
}
```

My code:

```typescript
const client = new SecretManagerServiceClient();
const secretName = "projects/688327991979/secrets/foobar";
const [accessResponse] = await client.accessSecretVersion({
    name: secretName,
});
```

The secret exists and has the following permissions/roles for the service account, that tries to access this secret:
- Secret Manager Secret Accessor
- Secret Manager Viewer

**Comment by raman-nbg** [comment]
Sorry, I just found my error. I have to specify the version in `secretName`.

Instead of `projects/688327991979/secrets/foobar` I have to use `projects/688327991979/secrets/foobar/versions/latest`
